### ISSUE TITLE
issue with main.js

### ISSUE THREAD

**Issue by Mystic018** [acocalypso/PokeSearchMad#1]
Hi, i have an issue with main.js :/
can you help me ?

Starting PokeSearch
Logged in as BOT - 
 - Language: english
channelID: 5699406490472...
mainChannelID: 569940649.....
Starting input validation...
valPkm: Geodude
SELECT * from pokemon_names WHERE english LIKE 'Geodude'; 
/PokeSearchMad/main.js:74
            if(rows1.length > 0){    
                     ^
TypeError: Cannot read property 'length' of undefined
    at Query.onResult (/PokeSearchMad/main.js:74:22)
    at Connection._notifyError (/PokeSearchMad/node_modules/mysql2/lib/connection.js:213:17)
    at Connection._handleFatalError (/PokeSearchMad/node_modules/mysql2/lib/connection.js:156:10)
    at Connection._handleNetworkError (/PokeSearchMad/node_modules/mysql2/lib/connection.js:169:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by acocalypso** [comment]
Sorry for the late reply, I'll take a look into it.

**Comment by acocalypso** [comment]
Starting input validation...
valPkm: geodude
SELECT * from pokemon_names WHERE english LIKE 'geodude';
TextRow {
  id: 74,
  german: 'Kleinstein',
  english: 'Geodude',
  japanese: 'Isitsubute'
}
checkInDB called
Pokemon entries found... getting data...
ResultCount: 3

Please drop the pokesearch db and recreate it with the db_pokesearch.js I guess you are using the old db version
